apiVersion: lattice.dev/v1alpha1
kind: LatticeService
metadata:
  name: jellyfin
  namespace: media
spec:
  workload:
    containers:
      main:
        image: docker.io/jellyfin/jellyfin:latest
        security:
          runAsUser: 0
          apparmorProfile: Unconfined
          allowedBinaries: ["*"]
        variables:
          JELLYFIN_PublishedServerUrl: "http://jellyfin.media.svc.cluster.local:8096"
        volumes:
          /config:
            source: ${resources.config}
          /cache:
            source: ${resources.cache}
          /media:
            source: ${resources.media-storage}
            path: library
          /tmp: {}
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 8096
    service:
      ports:
        http:
          port: 8096
          protocol: TCP
    resources:
      config:
        type: volume
        params:
          size: 10Gi
      cache:
        type: volume
        params:
          size: 20Gi
      # Shared media storage (OWNER - defines size and access policy)
      media-storage:
        type: volume
        id: media-storage
        params:
          size: 100Gi
          accessMode: ReadWriteOnce
          allowedConsumers:
            - sonarr
            - nzbget
      # External service dependencies
      jellyfin-repo:
        type: external-service
        direction: outbound
      # Service dependencies (bilateral agreement)
      sonarr:
        type: service
        direction: inbound
  replicas: 1
  ingress:
    routes:
      public:
        hosts:
          - jellyfin.home.arpa
        tls:
          issuerRef:
            name: letsencrypt-prod
