apiVersion: lattice.dev/v1alpha1
kind: LatticeService
metadata:
  name: jellyfin
  namespace: media
spec:
  environment: media
  containers:
    main:
      image: jellyfin/jellyfin:latest
      variables:
        JELLYFIN_PublishedServerUrl: "http://jellyfin.media.svc.cluster.local:8096"
      volumes:
        /config:
          source: ${resources.config}
        /cache:
          source: ${resources.cache}
        /media:
          source: ${resources.media-storage}
          path: library
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 4000m
          memory: 8Gi
      readinessProbe:
        httpGet:
          path: /health
          port: 8096
        initialDelaySeconds: 30
        periodSeconds: 10
  service:
    ports:
      http:
        port: 8096
        protocol: TCP
  resources:
    # Owned volumes (private to this service)
    config:
      type: volume
      params:
        size: 10Gi
        storageClass: local-path
    cache:
      type: volume
      params:
        size: 20Gi
        storageClass: local-path
    # Shared media storage (OWNER - has size)
    # Single volume with subdirectories for library and downloads
    # All services mount subpaths, co-located via pod affinity
    media-storage:
      type: volume
      id: media-storage
      params:
        size: 1500Gi
        storageClass: local-path
        accessMode: ReadWriteOnce
    # Service dependencies (bilateral agreement)
    sonarr:
      type: service
      direction: inbound
      inbound:
        rateLimit:
          requestsPerInterval: 100
          intervalSeconds: 60
  ingress:
    hosts:
      - jellyfin.home.local
    tls:
      mode: auto
      issuerRef:
        name: letsencrypt-prod
  replicas:
    min: 1
