apiVersion: lattice.dev/v1alpha1
kind: LatticeService
metadata:
  name: nzbget
  namespace: media
spec:
  environment: media
  containers:
    main:
      image: linuxserver/nzbget:latest
      variables:
        PUID: "1000"
        PGID: "1000"
        TZ: "America/New_York"
      volumes:
        /config:
          source: ${resources.config}
        /downloads:
          source: ${resources.downloads}
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 2000m
          memory: 2Gi
      readinessProbe:
        httpGet:
          path: /
          port: 6789
        initialDelaySeconds: 10
        periodSeconds: 10
  service:
    ports:
      http:
        port: 6789
        protocol: TCP
  resources:
    # Volume resources
    config:
      type: volume
      params:
        size: 1Gi
        storageClass: local-path
    downloads:
      type: volume
      params:
        size: 500Gi
        storageClass: local-path
        accessMode: ReadWriteMany
    # Service dependencies (bilateral agreement)
    sonarr:
      type: service
      direction: inbound
      inbound:
        rateLimit:
          requestsPerInterval: 1000
          intervalSeconds: 60
  replicas:
    min: 1
