# Nginx frontend - serves static HTML and proxies /api to the API service
# Outbound to: api
# Ingress-exposed at webapp.local
apiVersion: lattice.dev/v1alpha1
kind: LatticeService
metadata:
  name: frontend
  namespace: webapp
spec:
  replicas: 1
  workload:
    containers:
      main:
        image: nginx:1-alpine
        files:
          /etc/nginx/conf.d/default.conf:
            content: |
              server {
                  listen 80;
                  server_name _;

                  location / {
                      root /usr/share/nginx/html;
                      index index.html;
                  }

                  location /api/ {
                      proxy_pass http://api.webapp.svc.cluster.local:3000;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  }

                  location /health {
                      access_log off;
                      return 200 '{"status":"ok"}';
                      add_header Content-Type application/json;
                  }
              }
          /usr/share/nginx/html/index.html:
            content: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Lattice Webapp</title>
                <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                    background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
                    color: #e0e0e0;
                    min-height: 100vh;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                  }
                  .container {
                    text-align: center;
                    padding: 2rem;
                    background: rgba(255,255,255,0.05);
                    border-radius: 16px;
                    backdrop-filter: blur(10px);
                    border: 1px solid rgba(255,255,255,0.1);
                    max-width: 500px;
                    width: 90%;
                  }
                  h1 { font-size: 2rem; margin-bottom: 0.5rem; color: #fff; }
                  .subtitle { color: #aaa; margin-bottom: 1.5rem; }
                  .status {
                    padding: 1rem;
                    background: rgba(0,0,0,0.3);
                    border-radius: 8px;
                    font-family: monospace;
                    font-size: 0.9rem;
                    text-align: left;
                    white-space: pre-wrap;
                  }
                  .dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 6px; }
                  .dot.green { background: #4caf50; }
                  .dot.red { background: #f44336; }
                  .dot.loading { background: #ff9800; animation: pulse 1s infinite; }
                  @keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.3; } }
                </style>
              </head>
              <body>
                <div class="container">
                  <h1>Lattice Webapp</h1>
                  <p class="subtitle">Deployed with bilateral service mesh</p>
                  <div class="status" id="status"><span class="dot loading"></span>Connecting to API...</div>
                </div>
                <script>
                  fetch('/api/status')
                    .then(r => r.json())
                    .then(data => {
                      document.getElementById('status').innerHTML =
                        '<span class="dot green"></span>API: online\n' +
                        'Uptime: ' + Math.round(data.uptime) + 's\n' +
                        'Time: ' + data.timestamp;
                    })
                    .catch(() => {
                      document.getElementById('status').innerHTML =
                        '<span class="dot red"></span>API: unreachable';
                    });
                </script>
              </body>
              </html>
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
    service:
      ports:
        http:
          port: 80
          protocol: TCP
    resources:
      api:
        type: service
        direction: outbound
  ingress:
    routes:
      public:
        hosts:
          - webapp.local
